live_config_reload = true

[window]
opacity = 0.85
dynamic_padding = false
decorations = "buttonless"
option_as_alt = "Both"

  [window.dimensions]
  columns = 140
  lines = 45

  [window.padding]
  x = 8
  y = 8

[cursor]
blink_interval = 500

  [cursor.style]
  shape = "Block"
  blinking = "Always"

[font]
size = 18
# AppleFontSmoothing = true
# use_thin_strokes = true

  [font.normal]
  family = "FantasqueSansM Nerd Font"
  style = "Regular"

  [font.bold]
  family = "FantasqueSansM Nerd Font"
  style = "bold"

  [font.italic]
  family = "FantasqueSansM Nerd Font"
  style = "italic"

  [font.bold_italic]
  family = "FantasqueSansM Nerd Font"
  style = "bold_italic"

  [font.offset]
  x = 1
  y = 3

[colors.primary]
background = "#101421"
foreground = "#20e706"

[colors.normal]
black = "#2e2e2e"
red = "#eb4129"
green = "#abe047"
yellow = "#f6c744"
blue = "#47a0f3"
magenta = "#7b5cb0"
cyan = "#64dbed"
white = "#e5e9f0"

[colors.bright]
black = "#565656"
red = "#ec5357"
green = "#c0e17d"
yellow = "#f9da6a"
blue = "#49a4f8"
magenta = "#a47de9"
cyan = "#99faf2"
white = "#ffffff"
